name: quick_dashboard_shortcut
description: "A customizable dashboard shortcut grid widget for Flutter (icons/images + optional badge)."
version: 0.0.1
homepage: https://github.com/AmirSyauqi/quick_dashboard_shortcut
repository: https://github.com/AmirSyauqi/quick_dashboard_shortcut
issue_tracker: https://github.com/AmirSyauqi/quick_dashboard_shortcut/issues

environment:
  sdk: ^3.10.3
  flutter: ">=3.0.0"

dependencies:
  amicons: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
